/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Book: 宙に浮遊。Crystal よりリズム早く・上下の動き小さくして差別化。
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const FLOAT_SPEED = 1; // Crystal(2) より速い
const FLOAT_AMPLITUDE = 0.3; // Crystal(0.5) より小さく

export function Model(props) {
  const { position = [0, 0, 0], ...rest } = props;
  const groupRef = useRef(null);
  const { nodes } = useGLTF("/models/book-transformed.glb");

  useFrame((state) => {
    if (!groupRef.current) return;
    const [x, baseY, z] = position;
    groupRef.current.position.set(
      x,
      baseY + Math.sin(state.clock.elapsedTime * FLOAT_SPEED) * FLOAT_AMPLITUDE,
      z,
    );
  });

  return (
    <group ref={groupRef} {...rest} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload("/models/book-transformed.glb");
