/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 box.glb --transform 
Files: box.glb [8.48MB] > /Users/shogomorisawa/dev/personal/projects/portfolio/frontend/public/models/box-transformed.glb [873.8KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF("/models/box-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload("/models/box-transformed.glb")
