/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { STAGE } from "@/lib/world/config";

type GLTFResult = GLTF & {
  nodes: {
    Dome: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
  };
};

function Dome(props: React.ComponentPropsWithoutRef<"group">) {
  const { nodes } = useGLTF("/models/dome-transformed.glb") as GLTFResult;
  const matcap = useTexture("/textures/dome_texture.jpg");

  return (
    <group
      {...props}
      dispose={null}
      position={[0, STAGE.DOME_POSITION_Y, 0]}
    >
      <mesh geometry={nodes.Dome.geometry} scale={[1.8, 1.8, 1.8]}>
        <meshMatcapMaterial
          matcap={matcap}
          side={THREE.DoubleSide}
          color="#ffffff"
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/dome-transformed.glb");

export default Dome;
