/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { STAGE } from "@/lib/world/config";

type GLTFResult = GLTF & {
  nodes: {
    Floor: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
  };
};

interface FloorProps {
  groundRef: React.RefObject<THREE.Object3D | null>;
}

function Floor({
  groundRef,
  ...props
}: React.ComponentPropsWithoutRef<"group"> & FloorProps) {
  const { nodes } = useGLTF(
    "/models/floor-transformed.glb",
  ) as unknown as GLTFResult;
  const matcap = useTexture("/textures/floor_texture.jpg");

  return (
    <group
      ref={groundRef as React.RefObject<THREE.Group>}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Floor.geometry}
        scale={[STAGE.DOME_SCALE, STAGE.DOME_SCALE, STAGE.DOME_SCALE]}
      >
        <meshMatcapMaterial matcap={matcap} color="#ffffff" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/floor-transformed.glb");

export default Floor;
