import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { DotGothic16, Dancing_Script, Playfair_Display } from "next/font/google";
import { WebVitalsRegistry } from "@/components/providers/WebVitalsRegistry";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dotGothic16 = DotGothic16({
  weight: "400",
  variable: "--font-adventure",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  weight: "700",
  variable: "--font-dancing",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  weight: "400",
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dotGothic16.variable} ${dancingScript.variable} ${playfairDisplay.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <WebVitalsRegistry />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
