ServerName localhost
ServerSignature Off
ServerTokens Prod

<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride None
        Options -Indexes
        Require all granted
        FallbackResource /index.php
    </Directory>

    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    ErrorLog /proc/self/fd/2
    CustomLog /dev/null combined
</VirtualHost>
